### Generate random variables with `np.random.normal()`

Params:
- `loc` = mean (default=0)
- `scale` = standard deviation (default=1)
- `size` = how many independent random vars needed to be generated

For example, generate 50 independent random variables from a $N(0,1)$ distribution or normal distribution

In [12]:
import numpy as np

x = np.random.normal(size=50) # default
print(x)

x = np.random.normal(size=50, loc=20, scale=1) # N(20,1)
print(x)

[-1.99150236  0.69762416 -0.27102121 -0.90581272  0.1835564  -0.06617832
 -0.21617329  1.65059703 -1.08980437 -0.42573562 -0.78200443  0.83751291
 -0.98150627  0.6444548  -0.38414509 -1.65642058  0.74376687 -1.61314793
  0.68251613  0.75115694 -0.21737252  0.83263519 -0.55398245 -2.18303745
 -1.82865173 -0.05038227  1.08434034 -1.23072753 -0.1850681   2.20543426
  1.25793654 -1.16935129  0.7140734  -1.3488482   1.17083403 -2.08807614
 -0.92251776  0.21198432 -1.14429687  0.5056571   0.57574805  2.27610307
 -1.46823769  0.96527529  0.03175913  0.67081715 -0.82026132  1.34492878
  1.5568193   0.12428213]
[21.01274548 20.81963161 22.23019247 18.65124147 19.34401467 20.19670565
 20.38672426 19.84997868 20.88987816 18.90001467 20.21059729 19.63853938
 18.83644711 18.41947464 19.71777428 19.24906751 18.56808876 21.31630741
 19.75333136 19.19870907 19.87940941 19.9622213  20.34018735 20.46332763
 18.31266616 20.8786198  20.9620069  18.41982197 18.85597522 20.53151398
 18.49598447 18.39749772 

In [50]:
x1 = x
x2 = np.random.normal(size=50, loc=100, scale=2.5) # N(100, 2.5)
x3 = np.random.normal(size=50, loc=47, scale=0.2) # N(47, 0.2)
y = x1 + x2 + x3

# correlation matrix
print(np.corrcoef(x1,y))
print(np.corrcoef(x2,y))
print(np.corrcoef(x3,y))

[[1.         0.43437264]
 [0.43437264 1.        ]]
[[1.         0.93610232]
 [0.93610232 1.        ]]
[[1.         0.32415103]
 [0.32415103 1.        ]]


In [58]:
# seed
np.random.default_rng(3)

np.mean(y), y.mean()

(np.float64(166.22349852712796), np.float64(166.22349852712796))

In [59]:
np.var(y), y.var(), np.mean((y - y.mean())**2)

(np.float64(7.3857766960770865),
 np.float64(7.3857766960770865),
 np.float64(7.3857766960770865))