In [44]:
import numpy as np
import numpy.linalg as lga

In [45]:
np.random.seed(123)

X = np.random.rand(2,2) # square
U, S, Vt = lga.svd(X)

print("X =", X)
print()
print("U =", U)
print("S =", S)
print("Vt =", Vt)

U @ np.diag(S) @ Vt

X = [[0.69646919 0.28613933]
 [0.22685145 0.55131477]]

U = [[-0.81167379 -0.58411101]
 [-0.58411101  0.81167379]]
S = [0.89116166 0.35803002]
Vt = [[-0.78303661 -0.62197561]
 [-0.62197561  0.78303661]]


array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477]])

In [46]:
np.random.seed(123)

X = np.random.rand(5,3) # not square
U, S, Vt = lga.svd(X) # inside already has square matrix X.T @ X

print("X =", X)
print()
print("U =", U)
print("S =", S)
print("Vt =", Vt)

# U @ np.diag(S) @ Vt

X = [[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]
 [0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426]]

U = [[-0.37099483 -0.3524962   0.458687   -0.4089603  -0.60038901]
 [-0.47878359 -0.10216236 -0.67484955 -0.51745759  0.19273001]
 [-0.63369125 -0.3546081   0.05432555  0.6575224   0.1933947 ]
 [-0.40169627  0.80203124 -0.08083369  0.16974873 -0.4000466 ]
 [-0.26496154  0.31033572  0.56982363 -0.32224024  0.63635633]]
S = [2.01673733 0.47610086 0.38036897]
Vt = [[-0.70290043 -0.51482284 -0.49080385]
 [-0.41801681 -0.25929838  0.87064705]
 [ 0.57549363 -0.81714246  0.03294366]]


In [47]:
eigenvalues_L, eigenvectors_L = lga.eig(np.matmul(X, X.T)) # to get square
eigenvalues_L, eigenvectors_L 

(array([ 4.06722945e+00,  2.26672027e-01,  1.44680551e-01, -9.65314453e-17,
         5.73111536e-17]),
 array([[ 0.37099483,  0.3524962 ,  0.458687  ,  0.3157164 , -0.45530678],
        [ 0.47878359,  0.10216236, -0.67484955,  0.54026259,  0.33504058],
        [ 0.63369125,  0.3546081 ,  0.05432555, -0.62171071, -0.00642498],
        [ 0.40169627, -0.80203124, -0.08083369, -0.22701975, -0.43213814],
        [ 0.26496154, -0.31033572,  0.56982363,  0.41276787,  0.70260864]]))

the same results, with the caveat that some columns may differ by a factor of -1, and/or the order may be switched. This is normal, because flipping the direction of an eigenvector doesn’t change its physical significance nor anything about what it means to be an eigenvector. Also, eigenvectors obtained from np.linalg.eig may not be sorted by their eigenvalues, unlike that by np.linalg.svd.

In [48]:
print("U: ", U)
print("V: ", Vt.T)

vector = Vt[-1]
vector/np.min(vector)

U:  [[-0.37099483 -0.3524962   0.458687   -0.4089603  -0.60038901]
 [-0.47878359 -0.10216236 -0.67484955 -0.51745759  0.19273001]
 [-0.63369125 -0.3546081   0.05432555  0.6575224   0.1933947 ]
 [-0.40169627  0.80203124 -0.08083369  0.16974873 -0.4000466 ]
 [-0.26496154  0.31033572  0.56982363 -0.32224024  0.63635633]]
V:  [[-0.70290043 -0.41801681  0.57549363]
 [-0.51482284 -0.25929838 -0.81714246]
 [-0.49080385  0.87064705  0.03294366]]


array([-0.70427577,  1.        , -0.04031568])

In [53]:
k = 1
compressed_X = np.dot(U[:, :k], np.dot(np.diag(S[:k]), Vt[:k, :]))
X, compressed_X

# same dimension but smaller in data?

(array([[0.69646919, 0.28613933, 0.22685145],
        [0.55131477, 0.71946897, 0.42310646],
        [0.9807642 , 0.68482974, 0.4809319 ],
        [0.39211752, 0.34317802, 0.72904971],
        [0.43857224, 0.0596779 , 0.39804426]]),
 array([[0.52590949, 0.38519   , 0.36721901],
        [0.67870712, 0.49710301, 0.47391074],
        [0.89829889, 0.65793783, 0.62724183],
        [0.56943079, 0.41706615, 0.39760799],
        [0.37560034, 0.27509961, 0.26226488]]))